### ISSUE TITLE
Semi algebraic domains

### ISSUE THREAD

**Issue by AnderGray** [JuliaApproximation/DomainIntegrals.jl#8]
Hi, great package!

Is it possible to define a semialegric integration domain?

Something like 

`integral(f, x * y <= 1 for (x,y) in (0 .. 1)x(0 .. 1))`

where f: R^2 ->R ?

Cheers!

**Comment by daanhb** [comment]
Hi, thanks for your interest. Currently, this is not possible. There are two issues:
- `x * y <= 1 for (x,y) in (0..1) x (0..1)` defines a domain, but this syntax is not currently supported in DomainSets.jl. It looks neat though and it would be nice to make it possible. You essentially define a domain via its characteristic function, which is entirely compatible with how domains are defined in DomainSets.
- there is no package that I know of that can evaluate an integral without analytical knowledge of what the domain is. In this case, one would need to map the domain to a more standard one on which a standard adaptive quadrature can be applied. In the absence of that, something could be done if a bounding box is known (that would be the case here) but this would require a custom adaptive quadrature technique. Interesting feature, but not being developed just yet.

A short-term fix for your integral would be to parameterize the domain manually, and evaluate that integral using DomainIntegrals instead (or just using `hcubature` directly).

**Comment by AnderGray** [comment]
Did you say you are able to use the characteristic function?

You might be able to use: https://github.com/JuliaAlgebra/SemialgebraicSets.jl

**Comment by daanhb** [comment]
Thanks for the link, that looks relevant.

There is no method for arbitrary domains just yet (in fact several of the standard domains supported by DomainSets are still missing). However, if there is a bounding box and a characteristic function, then one could apply a trapezoidal rule based on taking regular grids on the bounding box and restricting the points to those that lie in the domain. This acts like a Riemann sum on the domain. It which would have very low order convergence, but if the boundary is smooth or has only isolated singularities, then a sequence of refinements would likely produce asymptotic behaviour of the error, and a sequence of approximations might be amenable to extrapolation. One does not need to know the expansion of the error, the fact that it exists may be sufficient.

That was my longer term plan anyway. It would be somewhat heuristic, probably not highly accurate and possibly slow - but there aren't a great many alternatives unless more is known about the domain. Possibly better methods could be devised specifically for semi-algebraic sets, because there you actually do have quite a bit of information.

**Comment by daanhb** [comment]
Meanwhile I've looked into generators and it is really quite cool. Right now (on master), you can write:
```julia
julia> integral(exp(x+y) for (x,y) in (0..1)^2)
2.9524924420120535
```
Also, with upcoming changes in DomainSets.jl, it will be possible to define a domain pretty much in the way you suggested above: `Domain(x * y <= 1 for (x,y) in (0 .. 1)x(0 .. 1) )`. It turns out that was really simple to do even, I had no idea.

Automatic integration, I don't know yet. But thanks at least for the syntax suggestions :-)

**Comment by AnderGray** [comment]
That's great! Thanks :D

**Comment by daanhb** [comment]
An update, something like this now works:
```julia
julia> integral(x->1, Domain( x+y <= 1 for (x,y) in (0..1) × (0..1) ) )
0.5000123377344884
```
The  accuracy is rather poor because the maximum number of function evaluations is fairly low. It can be adjusted:
```julia
julia> strategy = QuadAdaptive(maxevals=1e6)
QuadAdaptive{Float64}(0.0, 1.4901161193847656e-8, 1000000)

julia> integral(strategy,  x->1, Domain( x+y <= 1 for (x,y) in (0..1) × (0..1) ) )
0.49999929034549645

julia> abs(ans-1/2)
7.096545035500945e-7
```
The interface is a bit clunky, I'll have to rethink how to pass options in the interface (perhaps simply with keywords) and how to retrieve information about the number of function evaluations used etcetera.

It actually works differently from what I indicated above. The domain knows its bounding box, because you supply it with the `for` statement. The bounding box here is `[0,1]^2`. That is very useful information, because we can then extend the integrand from the simplex (in this example) to the box, simply by multiplying with the indicator function of the domain... In other words we extend by zero. This is likely to fail in many cases if the bounding box is not tight, because the integration package might miss it (if it only samples at points where the extended integrand vanishes, for example). It also yields discontinuities, of course, so it will be slow. But hey... it works ;-)

**Comment by AnderGray** [comment]
Super, and really useful!

Thanks for this update
